"""
This module implements VehicleClass class.
It is a concrete class and can directly initialize in the app.

Business Logic:
    - id is autogenerated and can't be changes.

Author: Peyman Khodabandehlouei
Date: 07-11-2025
"""

import uuid
from typing import List, Optional


class VehicleClass:
    """
    Concrete class representing a VehicleClass in the application.

    Args:
        name (str): The name of the VehicleClass.
        description (str): The description of the VehicleClass.
        base_daily_rate (float): The base daily rate of the VehicleClass.
        features (List[str]): The features of the VehicleClass.
        vehicle_class_id (Optional[str]): ID of the VehicleClass.

    Raises:
        TypeError: If any parameter has an incorrect type (name/description must be strings,
            base_daily_rate must be numeric, features must be a list of strings).
        ValueError: If base_daily_rate is not greater than zero.
    """

    def __init__(
        self,
        name: str,
        description: str,
        base_daily_rate: float,
        features: Optional[List[str]] = None,
        vehicle_class_id: Optional[str] = None,
    ) -> None:
        """Constructor for the VehicleClass class"""
        # Validate name
        if not isinstance(name, str):
            raise TypeError("name must be a string")

        # Validate description
        if not isinstance(description, str):
            raise TypeError("description must be a string")

        # Validate base_daily_rate
        if not isinstance(base_daily_rate, (int, float)):
            raise TypeError("base_daily_rate must be a numeric value")
        if base_daily_rate <= 0:
            raise ValueError("base_daily_rate must be greater than zero")

        # Validate features
        if features is None:
            features = []

        if not isinstance(features, list):
            raise TypeError("features must be a list of strings.")
        if not all(isinstance(feature, str) for feature in features):
            raise TypeError("all items in features must be string")

        # Validate id
        if vehicle_class_id is not None and not isinstance(vehicle_class_id, str):
            raise TypeError("vehicle_class_id must be a string.")
        if vehicle_class_id == "":
            raise ValueError("vehicle_class_id cannot be empty.")

        self.__id = (
            vehicle_class_id if vehicle_class_id is not None else str(uuid.uuid4())
        )
        self.__name = name
        self.__description = description
        self.__base_daily_rate = base_daily_rate
        self.__features = features.copy()

    @property
    def id(self) -> str:
        """Getter for the id property"""
        return self.__id

    @property
    def name(self) -> str:
        """Getter for the name property"""
        return self.__name

    @name.setter
    def name(self, name: str) -> None:
        """
        Setter for the name property

        Args:
            name (str): The name of the VehicleClass.

        Raises:
            TypeError: If name is not a string.
        """
        # Validation
        if not isinstance(name, str):
            raise TypeError("Name must be a string")

        # Logic
        self.__name = name

    @property
    def description(self) -> str:
        """Getter for description property"""
        return self.__description

    @description.setter
    def description(self, description: str) -> None:
        """
        Setter for description property

        Args:
            description (str): The description of the VehicleClass.

        Raises:
            TypeError: If description is not a string.
        """
        # Validation
        if not isinstance(description, str):
            raise TypeError("description must be a string")

        # Logic
        self.__description = description

    @property
    def base_daily_rate(self) -> float:
        """Getter for base_daily_rate property"""
        return self.__base_daily_rate

    @base_daily_rate.setter
    def base_daily_rate(self, base_daily_rate: float) -> None:
        """
        Setter for base_daily_rate property

        Args:
            base_daily_rate (float): The base daily rate of the VehicleClass.

        Raises:
            TypeError: If base_daily_rate is not a numeric value.
            ValueError: If base_daily_rate is not less than or equal to 0.
        """
        # Validation
        if not isinstance(base_daily_rate, (int, float)):
            raise TypeError("base_daily_rate rate must be a numeric value")
        if base_daily_rate <= 0:
            raise ValueError("base_daily_rate rate must be greater than zero")

        # Logic
        self.__base_daily_rate = base_daily_rate

    @property
    def features(self) -> List[str]:
        """Getter for features property"""
        return self.__features.copy()  # To prevent external modifications

    @features.setter
    def features(self, new_features: List[str]) -> None:
        """
        Setter for features property

        Args:
            new_features (List[str]): The new features of the VehicleClass.

        Raises:
            TypeError: If new_features is not a list.
            ValueError: If all items of new_features are not string.
        """
        if not isinstance(new_features, list):
            raise TypeError("features must be a list of strings.")
        if not all(isinstance(feature, str) for feature in new_features):
            raise TypeError("all items in features must be string")

        # Logic
        self.__features = new_features.copy()  # To prevent external modifications

    def add_feature(self, feature: str) -> None:
        """
        Adds a new feature to features property

        Args:
            feature (str): The new feature of the VehicleClass.

        Raises:
            TypeError: If feature is not a string.
            ValueError: If feature already exists in the VehicleClass.
        """
        # Validation
        if not isinstance(feature, str):
            raise TypeError("Feature must be a string.")
        if feature in self.__features:
            raise ValueError("Feature already exists.")

        # Logic
        self.__features.append(feature)

    def remove_feature(self, feature: str) -> None:
        """
        Removes a feature from features property

        Args:
            feature (str): The new feature of the VehicleClass.

        Raises:
            TypeError: If feature is not a string.
            ValueError: If feature does not exist in the VehicleClass.
        """
        # Validation
        if not isinstance(feature, str):
            raise TypeError("Feature must be a string.")
        if feature not in self.__features:
            raise ValueError("Feature does not exist.")

        # Logic
        self.__features.remove(feature)

    def has_feature(self, feature: str) -> bool:
        """
        Checks if a feature is in the features

        Args:
            feature (str): The new feature of the VehicleClass.

        Raises:
            TypeError: If feature is not a string.
        """
        # Validation
        if not isinstance(feature, str):
            raise TypeError("Feature must be a string.")

        # Logic
        return feature in self.__features

    def __str__(self):
        """String representation of the VehicleClass"""
        return f"VehicleClass(name={self.__name}, description={self.__description}, base_daily_rate={self.__base_daily_rate}, features={self.__features})"
