"""
This module implements InsuranceTier class
It is a concrete class and can directly initialize in the app.

Business Logic:
    - id is autogenerated and cannot be edited.

Author: Peyman Khodabandehlouei
Date: 07-11-2025
"""

import uuid
from typing import Optional


class InsuranceTier:
    """
    Concrete class representing an insurance tier in the application.
    This class can be directly initialized and used during application runtime.

    Args:
        tier_name (str): Name of the insurance tier.
        description (str): Description of the insurance tier.
        price_per_day (float): Price per day of the insurance tier.
        tier_id (str): ID of the insurance tier.

    Raises:
        TypeError: If any parameter has an incorrect type (tier_name/description must be strings, price_per_day must be numeric).
        ValueError: If price_per_day is negative.
    """

    def __init__(
        self,
        tier_name: str,
        description: str,
        price_per_day: float,
        tier_id: Optional[str] = None,
    ) -> None:
        # Validations
        if not isinstance(tier_name, str):
            raise TypeError("tier_name must be a string")
        if not isinstance(description, str):
            raise TypeError("description must be a string")
        if not isinstance(price_per_day, (int, float)):
            raise TypeError("price_per_day must be a numeric value")
        if price_per_day < 0:
            raise ValueError("price_per_day cannot be negative")

        # Validate id
        if tier_id is not None and not isinstance(tier_id, str):
            raise TypeError("tier_id must be a string.")
        if tier_id == "":
            raise ValueError("tier_id cannot be empty.")

        # Assign values
        self.__id = tier_id if tier_id is not None else str(uuid.uuid4())
        self.__tier_name = tier_name
        self.__description = description
        self.__price_per_day = price_per_day

    @property
    def id(self) -> str:
        """Getter method for id property."""
        return self.__id

    @property
    def tier_name(self) -> str:
        """Getter method for tier_name property."""
        return self.__tier_name

    @tier_name.setter
    def tier_name(self, tier_name: str) -> None:
        """Setter method for tier_name property."""
        # Validation
        if not isinstance(tier_name, str):
            raise TypeError("tier_name must be a string")

        self.__tier_name = tier_name

    @property
    def description(self) -> str:
        """Getter method for description property."""
        return self.__description

    @description.setter
    def description(self, description: str) -> None:
        """Setter method for description property."""
        # Validation
        if not isinstance(description, str):
            raise TypeError("description must be a string")

        self.__description = description

    @property
    def price_per_day(self) -> float:
        """Getter method for price_per_day property."""
        return self.__price_per_day

    @price_per_day.setter
    def price_per_day(self, price_per_day: float) -> None:
        """Setter method for price_per_day property."""
        # Validation
        if not isinstance(price_per_day, (int, float)):
            raise TypeError("price_per_day must be a numeric value")
        if price_per_day < 0:
            raise ValueError("price_per_day cannot be negative")

        self.__price_per_day = price_per_day

    def __str__(self):
        """String representation of the InsuranceTier object."""
        return f"InsuranceTier(tier_name={self.__tier_name}, description={self.__description}, price_per_day={self.__price_per_day})"
