"""
This module implements AddOn class
It is a concrete class and can directly initialize in the app.

Business Logic:
    - id is autogenerated and cannot be edited.

Author: Peyman Khodabandehlouei
Date: 07-11-2025
"""

import uuid
from typing import Optional


class AddOn:
    """
    Concrete class representing an add-on in the application.
    This class can be directly initialized and used during application runtime.

    Args:
        name (str): Name of the add-on.
        description (str): Description of the add-on.
        price_per_day (float): Price per day of the add-on.
        addon_id (Optional[str]): ID of the add-on.

    Raises:
        TypeError: If any parameter has an incorrect type (name/description must be strings, price_per_day must be numeric).
        ValueError: If price_per_day is negative.
    """

    def __init__(
        self,
        name: str,
        description: str,
        price_per_day: float,
        addon_id: Optional[str] = None,
    ) -> None:
        # Validations
        if not isinstance(name, str):
            raise TypeError("name must be a string")
        if not isinstance(description, str):
            raise TypeError("description must be a string")
        if not isinstance(price_per_day, (int, float)):
            raise TypeError("price_per_day must be a numeric value")
        if price_per_day < 0:
            raise ValueError("price_per_day cannot be negative")

        # Validate id
        if addon_id is not None and not isinstance(addon_id, str):
            raise TypeError("addon_id must be a string.")
        if addon_id == "":
            raise ValueError("addon_id cannot be empty.")

        # Assign values
        self.__id = addon_id if addon_id is not None else str(uuid.uuid4())
        self.__name = name
        self.__description = description
        self.__price_per_day = price_per_day

    @property
    def id(self) -> str:
        """Getter method for id property."""
        return self.__id

    @property
    def name(self) -> str:
        """Getter method for name property."""
        return self.__name

    @name.setter
    def name(self, name: str) -> None:
        """Setter method for name property."""
        # Validation
        if not isinstance(name, str):
            raise TypeError("name must be a string")

        self.__name = name

    @property
    def description(self) -> str:
        """Getter method for description property."""
        return self.__description

    @description.setter
    def description(self, description: str) -> None:
        """Setter method for description property."""
        # Validation
        if not isinstance(description, str):
            raise TypeError("description must be a string")

        self.__description = description

    @property
    def price_per_day(self) -> float:
        """Getter method for price_per_day property."""
        return self.__price_per_day

    @price_per_day.setter
    def price_per_day(self, price_per_day: float) -> None:
        """Setter method for price_per_day property."""
        # Validation
        if not isinstance(price_per_day, (int, float)):
            raise TypeError("price_per_day must be a numeric value")
        if price_per_day < 0:
            raise ValueError("price_per_day cannot be negative")

        self.__price_per_day = price_per_day

    def __str__(self):
        """String representation of the AddOn object."""
        return f"AddOn(name={self.__name}, description={self.__description}, price_per_day={self.__price_per_day})"
